REM   Script: t1
REM   TESTANDO CRIAÇÃO

CREATE TABLE CLIENTE( 
    ID INT, --deixei como int mas tô em duvida se boto como varchar 
    NOME VARCHAR(100) NOT NULL, 
    FONE VARCHAR(11), 
    ENDERECO VARCHAR(150), 
    CONSTRAINT PK_CLIENTE PRIMARY KEY(ID) 
);

CREATE TABLE MOTORISTA( 
    CPF VARCHAR(11), 
    NOME VARCHAR(100) NOT NULL, 
    CNH VARCHAR(9) UNIQUE NOT NULL, 
    DATA_CONTR DATE, 
    SUPERVISOR VARCHAR(11), 
    CONSTRAINT PK_MOTORISTA PRIMARY KEY (CPF), 
    CONSTRAINT FK_MOTORISTA_SUPERVISOR FOREIGN KEY (SUPERVISOR) REFERENCES MOTORISTA(CPF) 
);

CREATE TABLE TRANSPORTE( 
    COD INT,  
    TIPO VARCHAR(100), 
    CAPACIDADE INT, 
    COR VARCHAR(100), 
    PLACA VARCHAR(100), 
    CONSTRAINT PK_TRANS PRIMARY KEY(COD) 
);

CREATE TABLE CARACTERISTICA( 
    ID INT, 
    ACIDEZ VARCHAR(100), 
    TORRA VARCHAR(100), 
    CORPO VARCHAR(100), 
    MOAGEM VARCHAR(100), 
    CONSTRAINT PK_CARAC PRIMARY KEY(ID) 
);

CREATE TABLE CAFE( 
    COD INT,  
    NOME VARCHAR(100) NOT NULL, 
    FAZENDA VARCHAR(100), 
    PRECO NUMBER(5, 2), 
    ID INT UNIQUE, 
    CONSTRAINT FK_CAFE_CARAC FOREIGN KEY (ID) REFERENCES CARACTERISTICA(ID) ON DELETE CASCADE, -- posso estar errada mas acho q ta certo 
    CONSTRAINT PK_CAFE PRIMARY KEY(COD) 
);

CREATE TABLE PROMOCAO( 
    ID INT, 
    VALOR NUMBER(5, 2) NOT NULL, 
    CONSTRAINT PK_PROMO PRIMARY KEY(ID) 
);

CREATE TABLE PEDIDO( 
    ID INT, 
    NUM INT, 
    DAT DATE, 
    PRECO_FINAL NUMBER(5, 2), 
    QUANT INT, 
    DESCONTO NUMBER(5, 2), 
    CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (ID) REFERENCES CLIENTE(ID) ON DELETE CASCADE, 
    CONSTRAINT PK_PEDIDO PRIMARY KEY (ID, NUM) 
);

CREATE TABLE PF( 
    ID INT, 
    CPF CHAR(11) NOT NULL, 
    DATA_NASC DATE, 
    CONSTRAINT FK_PF_CLIENTE FOREIGN KEY (ID) REFERENCES CLIENTE(ID) ON DELETE CASCADE, 
    CONSTRAINT PK_PF PRIMARY KEY (ID) 
);

CREATE TABLE PJ( 
    ID INT, 
    RAZAO_SOCIAL VARCHAR(100), 
    CNPJ CHAR(14) NOT NULL, 
    CONSTRAINT FK_PJ_CLIENTE FOREIGN KEY (ID) REFERENCES CLIENTE(ID) ON DELETE CASCADE, 
    CONSTRAINT PK_PJ PRIMARY KEY (ID) 
);

CREATE TABLE RA( 
    ID INT, 
    COD_REV VARCHAR(100), 
    AREA_COB VARCHAR(100), 
    CONSTRAINT FK_RA_PF FOREIGN KEY (ID) REFERENCES PF(ID) ON DELETE CASCADE, 
    CONSTRAINT PK_RA PRIMARY KEY (ID) 
);

CREATE TABLE TEM( 
    ID INT, 
    NUM INT, 
    COD INT, 
    CONSTRAINT FK_PEDIDO_CAFE FOREIGN KEY (ID, NUM) REFERENCES PEDIDO(ID, NUM) ON DELETE CASCADE, 
    CONSTRAINT FK_TEM_CAFE FOREIGN KEY (COD) REFERENCES CAFE(COD) ON DELETE CASCADE, 
    CONSTRAINT PK_TEM PRIMARY KEY (ID, NUM, COD) 
);

CREATE OR REPLACE TRIGGER disjuncao_pf 
BEFORE INSERT OR UPDATE ON PF 
FOR EACH ROW 
DECLARE 
    v_count NUMBER; 
BEGIN 
    SELECT COUNT(*) INTO v_count 
    FROM PJ 
    WHERE Id = :NEW.Id; 
 
    IF v_count > 0 THEN 
        RAISE_APPLICATION_ERROR(-20001, 'cliente já está em PJ.'); 
    END IF; 
END;  
/

CREATE OR REPLACE TRIGGER disjuncao_pj 
BEFORE INSERT OR UPDATE ON PJ 
FOR EACH ROW 
DECLARE 
    v_count NUMBER; 
BEGIN 
    SELECT COUNT(*) INTO v_count 
    FROM PF 
    WHERE Id = :NEW.Id; 
 
    IF v_count > 0 THEN 
        RAISE_APPLICATION_ERROR(-20002, 'cliente já está em PF.'); 
    END IF; 
END; 
/

CREATE TABLE Entrega ( 
Id_pedido INT, 
Num INT, 
CPF VARCHAR(11), 
Codigo INT, 
Status VARCHAR(20), 
Data DATE, 
CONSTRAINT pk_entrega PRIMARY KEY (Id_pedido, Num, CPF, Codigo), 
CONSTRAINT fk_entrega_pedido FOREIGN KEY (Id_pedido, Num) REFERENCES 
Pedido(ID, NUM), 
CONSTRAINT fk_entrega_motorista FOREIGN KEY (CPF) REFERENCES 
Motorista(CPF), 
CONSTRAINT fk_entrega_transporte FOREIGN KEY (Codigo) REFERENCES 
Transporte(COD) 
);

INSERT ALL
  INTO CLIENTE(ID, NOME, FONE, ENDERECO) VALUES (1, 'João Silva', '11987654321', 'Rua das Flores, 123, São Paulo, SP')
  INTO CLIENTE(ID, NOME, FONE, ENDERECO) VALUES (2, 'Maria Oliveira', '21988776655', 'Avenida Copacabana, 456, Rio de Janeiro, RJ')
  INTO CLIENTE(ID, NOME, FONE, ENDERECO) VALUES (3, 'Carlos Pereira', '31999887766', 'Rua da Bahia, 789, Belo Horizonte, MG')
  INTO CLIENTE(ID, NOME, FONE, ENDERECO) VALUES (4, 'Ana Costa', '51981234567', 'Avenida Ipiranga, 101, Porto Alegre, RS')
  INTO CLIENTE(ID, NOME, FONE, ENDERECO) VALUES (5, 'Beatriz Souza', '71996543210', 'Rua do Carmo, 212, Salvador, BA')
  INTO CLIENTE(ID, NOME, FONE, ENDERECO) VALUES (6, 'Cafeteria Sabor & Arte Ltda', '1145678901', 'Alameda Santos, 1500, São Paulo, SP')
  INTO CLIENTE(ID, NOME, FONE, ENDERECO) VALUES (7, 'Empório Grão Nobre', '4133445566', 'Rua XV de Novembro, 300, Curitiba, PR')
  INTO CLIENTE(ID, NOME, FONE, ENDERECO) VALUES (8, 'Mercado Central Comércio de Alimentos', '6132145678', 'Setor Comercial Sul, Quadra 2, Brasília, DF')
  INTO CLIENTE(ID, NOME, FONE, ENDERECO) VALUES (9, 'Distribuidora Aroma do Campo', '8134567890', 'Avenida Boa Viagem, 550, Recife, PE')
  INTO CLIENTE(ID, NOME, FONE, ENDERECO) VALUES (10, 'Padaria Doce Manhã Eireli', '2733221100', 'Rua Sete de Setembro, 80, Vitória, ES')
SELECT * FROM dual;


-- Inserindo dados na tabela PF (Pessoa Física)
INSERT ALL
  INTO PF(ID, CPF, DATA_NASC) VALUES (1, '11122233344', TO_DATE('1985-05-20', 'YYYY-MM-DD'))
  INTO PF(ID, CPF, DATA_NASC) VALUES (2, '22233344455', TO_DATE('1990-11-15', 'YYYY-MM-DD'))
  INTO PF(ID, CPF, DATA_NASC) VALUES (3, '33344455566', TO_DATE('1978-02-10', 'YYYY-MM-DD'))
  INTO PF(ID, CPF, DATA_NASC) VALUES (4, '44455566677', TO_DATE('1995-07-30', 'YYYY-MM-DD'))
  INTO PF(ID, CPF, DATA_NASC) VALUES (5, '55566677788', TO_DATE('2000-01-05', 'YYYY-MM-DD'))
SELECT * FROM dual;


-- Inserindo dados na tabela PJ (Pessoa Jurídica)
INSERT ALL
  INTO PJ(ID, RAZAO_SOCIAL, CNPJ) VALUES (6, 'Cafeteria Sabor & Arte Ltda', '11222333000144')
  INTO PJ(ID, RAZAO_SOCIAL, CNPJ) VALUES (7, 'Empório Grão Nobre e Cia', '22333444000155')
  INTO PJ(ID, RAZAO_SOCIAL, CNPJ) VALUES (8, 'Mercado Central Comércio de Alimentos S.A.', '33444555000166')
  INTO PJ(ID, RAZAO_SOCIAL, CNPJ) VALUES (9, 'Distribuidora Aroma do Campo Ltda', '44555666000177')
  INTO PJ(ID, RAZAO_SOCIAL, CNPJ) VALUES (10, 'Padaria Doce Manhã Eireli', '55666777000188')
SELECT * FROM dual;


-- Inserindo dados na tabela RA (Representante Autônomo)
-- Apenas alguns clientes PF são representantes
INSERT ALL
  INTO RA(ID, COD_REV, AREA_COB) VALUES (3, 'REV-MG-001', 'Belo Horizonte e Região Metropolitana')
  INTO RA(ID, COD_REV, AREA_COB) VALUES (4, 'REV-RS-001', 'Porto Alegre e Vale dos Sinos')
SELECT * FROM dual;


-- Inserindo dados na tabela MOTORISTA
-- Note que os dois primeiros não possuem supervisor. Os demais são supervisionados por eles.
INSERT ALL
  INTO MOTORISTA(CPF, NOME, CNH, DATA_CONTR, SUPERVISOR) VALUES ('12345678901', 'Roberto Dias', '123456789', TO_DATE('2020-03-15', 'YYYY-MM-DD'), NULL)
  INTO MOTORISTA(CPF, NOME, CNH, DATA_CONTR, SUPERVISOR) VALUES ('23456789012', 'Fernanda Lima', '234567890', TO_DATE('2019-07-20', 'YYYY-MM-DD'), NULL)
  INTO MOTORISTA(CPF, NOME, CNH, DATA_CONTR, SUPERVISOR) VALUES ('34567890123', 'Marcos Andrade', '345678901', TO_DATE('2021-01-10', 'YYYY-MM-DD'), '12345678901')
  INTO MOTORISTA(CPF, NOME, CNH, DATA_CONTR, SUPERVISOR) VALUES ('45678901234', 'Juliana Santos', '456789012', TO_DATE('2022-05-22', 'YYYY-MM-DD'), '23456789012')
  INTO MOTORISTA(CPF, NOME, CNH, DATA_CONTR, SUPERVISOR) VALUES ('56789012345', 'Ricardo Martins', '567890123', TO_DATE('2022-11-01', 'YYYY-MM-DD'), '12345678901')
  INTO MOTORISTA(CPF, NOME, CNH, DATA_CONTR, SUPERVISOR) VALUES ('67890123456', 'Laura Azevedo', '678901234', TO_DATE('2023-02-18', 'YYYY-MM-DD'), '23456789012')
  INTO MOTORISTA(CPF, NOME, CNH, DATA_CONTR, SUPERVISOR) VALUES ('78901234567', 'Bruno Carvalho', '789012345', TO_DATE('2023-06-30', 'YYYY-MM-DD'), '12345678901')
  INTO MOTORISTA(CPF, NOME, CNH, DATA_CONTR, SUPERVISOR) VALUES ('89012345678', 'Vanessa Rocha', '890123456', TO_DATE('2023-08-14', 'YYYY-MM-DD'), '23456789012')
  INTO MOTORISTA(CPF, NOME, CNH, DATA_CONTR, SUPERVISOR) VALUES ('90123456789', 'Felipe Barros', '901234567', TO_DATE('2024-01-20', 'YYYY-MM-DD'), '12345678901')
  INTO MOTORISTA(CPF, NOME, CNH, DATA_CONTR, SUPERVISOR) VALUES ('01234567890', 'Camila Neves', '012345678', TO_DATE('2024-03-05', 'YYYY-MM-DD'), '23456789012')
SELECT * FROM dual;


-- Inserindo dados na tabela TRANSPORTE
INSERT ALL
  INTO TRANSPORTE(COD, TIPO, CAPACIDADE, COR, PLACA) VALUES (10, 'Van de Carga', 1500, 'Branca', 'BRA1A23')
  INTO TRANSPORTE(COD, TIPO, CAPACIDADE, COR, PLACA) VALUES (20, 'Caminhão Leve', 4000, 'Prata', 'MER2B34')
  INTO TRANSPORTE(COD, TIPO, CAPACIDADE, COR, PLACA) VALUES (30, 'Fiorino', 650, 'Branca', 'SUL3C45')
  INTO TRANSPORTE(COD, TIPO, CAPACIDADE, COR, PLACA) VALUES (40, 'Caminhão Toco', 8000, 'Vermelho', 'BRA4D56')
  INTO TRANSPORTE(COD, TIPO, CAPACIDADE, COR, PLACA) VALUES (50, 'Van de Carga', 1500, 'Azul', 'MER5E67')
  INTO TRANSPORTE(COD, TIPO, CAPACIDADE, COR, PLACA) VALUES (60, 'Kombi Carga', 1000, 'Branca', 'SUL6F78')
  INTO TRANSPORTE(COD, TIPO, CAPACIDADE, COR, PLACA) VALUES (70, 'Caminhão Truck', 14000, 'Verde', 'BRA7G89')
  INTO TRANSPORTE(COD, TIPO, CAPACIDADE, COR, PLACA) VALUES (80, 'Fiorino', 650, 'Prata', 'MER8H90')
  INTO TRANSPORTE(COD, TIPO, CAPACIDADE, COR, PLACA) VALUES (90, 'Van de Carga', 1500, 'Preta', 'SUL9I01')
  INTO TRANSPORTE(COD, TIPO, CAPACIDADE, COR, PLACA) VALUES (100, 'Caminhão Leve', 4000, 'Amarelo', 'BRA0J12')
SELECT * FROM dual;


-- Inserindo dados na tabela CARACTERISTICA
INSERT ALL
  INTO CARACTERISTICA(ID, ACIDEZ, TORRA, CORPO, MOAGEM) VALUES (101, 'Cítrica Média', 'Média Clara', 'Leve', 'Média')
  INTO CARACTERISTICA(ID, ACIDEZ, TORRA, CORPO, MOAGEM) VALUES (102, 'Frutada Baixa', 'Escura', 'Encorpado', 'Grossa')
  INTO CARACTERISTICA(ID, ACIDEZ, TORRA, CORPO, MOAGEM) VALUES (103, 'Brilhante Alta', 'Média', 'Delicado', 'Fina')
  INTO CARACTERISTICA(ID, ACIDEZ, TORRA, CORPO, MOAGEM) VALUES (104, 'Equilibrada', 'Média', 'Cremoso', 'Média')
  INTO CARACTERISTICA(ID, ACIDEZ, TORRA, CORPO, MOAGEM) VALUES (105, 'Baixa', 'Clara', 'Suave', 'Média')
  INTO CARACTERISTICA(ID, ACIDEZ, TORRA, CORPO, MOAGEM) VALUES (106, 'Cítrica Alta', 'Média', 'Viloso', 'Fina')
  INTO CARACTERISTICA(ID, ACIDEZ, TORRA, CORPO, MOAGEM) VALUES (107, 'Achocolatada', 'Escura', 'Pesado', 'Grossa')
  INTO CARACTERISTICA(ID, ACIDEZ, TORRA, CORPO, MOAGEM) VALUES (108, 'Floral', 'Clara', 'Leve', 'Média')
  INTO CARACTERISTICA(ID, ACIDEZ, TORRA, CORPO, MOAGEM) VALUES (109, 'Caramelizada', 'Média Escura', 'Encorpado', 'Média')
  INTO CARACTERISTICA(ID, ACIDEZ, TORRA, CORPO, MOAGEM) VALUES (110, 'Suave', 'Média Clara', 'Aveludado', 'Fina')
SELECT * FROM dual;


-- Inserindo dados na tabela CAFE
INSERT ALL
  INTO CAFE(COD, NOME, FAZENDA, PRECO, ID) VALUES (1001, 'Bourbon Amarelo', 'Fazenda Mantiqueira', 55.00, 101)
  INTO CAFE(COD, NOME, FAZENDA, PRECO, ID) VALUES (1002, 'Catuaí Vermelho', 'Sítio Caparaó', 75.50, 102)
  INTO CAFE(COD, NOME, FAZENDA, PRECO, ID) VALUES (1003, 'Geisha', 'Fazenda Esmeralda', 120.00, 103)
  INTO CAFE(COD, NOME, FAZENDA, PRECO, ID) VALUES (1004, 'Mundo Novo', 'Fazenda Cerrado Mineiro', 48.90, 104)
  INTO CAFE(COD, NOME, FAZENDA, PRECO, ID) VALUES (1005, 'Arábica Orgânico', 'Sítio Boa Esperança', 62.00, 105)
  INTO CAFE(COD, NOME, FAZENDA, PRECO, ID) VALUES (1006, 'Kona', 'Kona Coffee Farms', 150.75, 106)
  INTO CAFE(COD, NOME, FAZENDA, PRECO, ID) VALUES (1007, 'Robusta Especial', 'Plantação do Congo', 40.00, 107)
  INTO CAFE(COD, NOME, FAZENDA, PRECO, ID) VALUES (1008, 'Yirgacheffe', 'Cooperativa Etíope', 95.20, 108)
  INTO CAFE(COD, NOME, FAZENDA, PRECO, ID) VALUES (1009, 'Sul de Minas', 'Fazenda Santa Inês', 59.99, 109)
  INTO CAFE(COD, NOME, FAZENDA, PRECO, ID) VALUES (1100, 'Microlote Premiado', 'Sítio da Torre', 180.00, 110)
SELECT * FROM dual;


-- Inserindo dados na tabela PROMOCAO
INSERT ALL
  INTO PROMOCAO(ID, VALOR) VALUES (1, 5.00)
  INTO PROMOCAO(ID, VALOR) VALUES (2, 10.00)
  INTO PROMOCAO(ID, VALOR) VALUES (3, 15.50)
  INTO PROMOCAO(ID, VALOR) VALUES (4, 20.00)
  INTO PROMOCAO(ID, VALOR) VALUES (5, 25.00)
  INTO PROMOCAO(ID, VALOR) VALUES (6, 0.50)
  INTO PROMOCAO(ID, VALOR) VALUES (7, 1.00)
  INTO PROMOCAO(ID, VALOR) VALUES (8, 2.00)
  INTO PROMOCAO(ID, VALOR) VALUES (9, 3.00)
  INTO PROMOCAO(ID, VALOR) VALUES (10, 4.00)
SELECT * FROM dual;


-- Inserindo dados na tabela PEDIDO
INSERT ALL
  INTO PEDIDO(ID, NUM, DAT, PRECO_FINAL, QUANT, DESCONTO) VALUES (1, 101, TO_DATE('2024-05-10', 'YYYY-MM-DD'), 110.00, 2, 0.00)
  INTO PEDIDO(ID, NUM, DAT, PRECO_FINAL, QUANT, DESCONTO) VALUES (2, 102, TO_DATE('2024-05-12', 'YYYY-MM-DD'), 48.90, 1, 0.00)
  INTO PEDIDO(ID, NUM, DAT, PRECO_FINAL, QUANT, DESCONTO) VALUES (6, 103, TO_DATE('2024-05-15', 'YYYY-MM-DD'), 370.00, 5, 25.00)
  INTO PEDIDO(ID, NUM, DAT, PRECO_FINAL, QUANT, DESCONTO) VALUES (3, 104, TO_DATE('2024-06-01', 'YYYY-MM-DD'), 124.00, 2, 0.00)
  INTO PEDIDO(ID, NUM, DAT, PRECO_FINAL, QUANT, DESCONTO) VALUES (7, 105, TO_DATE('2024-06-05', 'YYYY-MM-DD'), 489.00, 10, 0.00)
  INTO PEDIDO(ID, NUM, DAT, PRECO_FINAL, QUANT, DESCONTO) VALUES (4, 106, TO_DATE('2024-06-20', 'YYYY-MM-DD'), 150.75, 1, 0.00)
  INTO PEDIDO(ID, NUM, DAT, PRECO_FINAL, QUANT, DESCONTO) VALUES (8, 107, TO_DATE('2024-07-02', 'YYYY-MM-DD'), 119.98, 2, 0.00)
  INTO PEDIDO(ID, NUM, DAT, PRECO_FINAL, QUANT, DESCONTO) VALUES (1, 108, TO_DATE('2024-07-11', 'YYYY-MM-DD'), 75.50, 1, 0.00)
  INTO PEDIDO(ID, NUM, DAT, PRECO_FINAL, QUANT, DESCONTO) VALUES (9, 109, TO_DATE('2024-07-15', 'YYYY-MM-DD'), 200.00, 5, 0.00)
  INTO PEDIDO(ID, NUM, DAT, PRECO_FINAL, QUANT, DESCONTO) VALUES (10, 110, TO_DATE('2024-07-22', 'YYYY-MM-DD'), 180.00, 1, 0.00)
SELECT * FROM dual;


-- Inserindo dados na tabela TEM (itens do pedido)
INSERT ALL
  INTO TEM(ID, NUM, COD) VALUES (1, 101, 1001) -- João comprou 2x Bourbon Amarelo
  INTO TEM(ID, NUM, COD) VALUES (2, 102, 1004) -- Maria comprou 1x Mundo Novo
  INTO TEM(ID, NUM, COD) VALUES (6, 103, 1002) -- Cafeteria Sabor & Arte comprou 5x Catuaí Vermelho
  INTO TEM(ID, NUM, COD) VALUES (3, 104, 1005) -- Carlos comprou 2x Arábica Orgânico
  INTO TEM(ID, NUM, COD) VALUES (7, 105, 1004) -- Empório Grão Nobre comprou 10x Mundo Novo
  INTO TEM(ID, NUM, COD) VALUES (4, 106, 1006) -- Ana comprou 1x Kona
  INTO TEM(ID, NUM, COD) VALUES (8, 107, 1009) -- Mercado Central comprou 2x Sul de Minas
  INTO TEM(ID, NUM, COD) VALUES (1, 108, 1002) -- João fez outro pedido, 1x Catuaí Vermelho
  INTO TEM(ID, NUM, COD) VALUES (9, 109, 1007) -- Distribuidora comprou 5x Robusta Especial
  INTO TEM(ID, NUM, COD) VALUES (10, 110, 1100) -- Padaria comprou 1x Microlote Premiado
SELECT * FROM dual;


INSERT ALL
  INTO Entrega(Id_pedido, Num, CPF, Codigo, Status, Data) VALUES (1, 101, '12345678901', 30, 'Entregue', TO_DATE('2024-05-12', 'YYYY-MM-DD'))
  INTO Entrega(Id_pedido, Num, CPF, Codigo, Status, Data) VALUES (2, 102, '34567890123', 30, 'Entregue', TO_DATE('2024-05-14', 'YYYY-MM-DD'))
  INTO Entrega(Id_pedido, Num, CPF, Codigo, Status, Data) VALUES (6, 103, '23456789012', 20, 'Entregue', TO_DATE('2024-05-18', 'YYYY-MM-DD'))
  INTO Entrega(Id_pedido, Num, CPF, Codigo, Status, Data) VALUES (3, 104, '45678901234', 10, 'Entregue', TO_DATE('2024-06-03', 'YYYY-MM-DD'))
  INTO Entrega(Id_pedido, Num, CPF, Codigo, Status, Data) VALUES (7, 105, '56789012345', 40, 'Entregue', TO_DATE('2024-06-08', 'YYYY-MM-DD'))
  INTO Entrega(Id_pedido, Num, CPF, Codigo, Status, Data) VALUES (4, 106, '67890123456', 80, 'Em trânsito', TO_DATE('2024-06-21', 'YYYY-MM-DD'))
  INTO Entrega(Id_pedido, Num, CPF, Codigo, Status, Data) VALUES (8, 107, '78901234567', 10, 'Aguardando envio', TO_DATE('2024-07-03', 'YYYY-MM-DD'))
  INTO Entrega(Id_pedido, Num, CPF, Codigo, Status, Data) VALUES (1, 108, '89012345678', 30, 'Processando', TO_DATE('2024-07-12', 'YYYY-MM-DD'))
  INTO Entrega(Id_pedido, Num, CPF, Codigo, Status, Data) VALUES (9, 109, '90123456789', 50, 'Em trânsito', TO_DATE('2024-07-17', 'YYYY-MM-DD'))
  INTO Entrega(Id_pedido, Num, CPF, Codigo, Status, Data) VALUES (10, 110, '01234567890', 60, 'Entregue', TO_DATE('2024-07-25', 'YYYY-MM-DD'))
SELECT * FROM dual;


